kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-persvol
spec:
  storageClassName: my-disk
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/
